guest=['mama','father','grandpa','the futural wife']
uncomfortable_person=guest.pop(-1)
print(uncomfortable_person.title())
guest.insert(3,'uncle')
print(guest)
guest.insert(0,'longmao')
guest.insert(3,'ant')
guest.insert(-1,'friends')
guest.append('classmates')
print(guest)
print("I am very sorry to tell you that I only can invite two person to enjoy the dinner")
message="Sorry to tell you a pity message"
first_=guest.pop(-1)
second_=guest.pop(-2)
third_=guest.pop(-3)
fourth_=guest.pop(-4)
fifth_=guest.pop(0)
sixth_=guest.pop(2)
print(first_,message)
print(second_,message)
print(third_,message)
print(fourth_,message)
print(fifth_,message)
print(sixth_,message)
message2="I am happy to enjoy the dinner with you!"
print(f"{guest[0]} welcome to my home","\n\t",message2)
print(len(guest))